application:
  locations:
    - mac: ""
      host: home.local
      ip: 192.168.3.109
      port: 22
      username: teraf
      password: 1q2w3e4r!!
    - mac: ""
      host: home.local
      ip: 192.168.3.109
      port: 23
      username: user
      password: adminX
      killCommand: "echo 'adminX' | sudo -S shutdown +1"
    - mac: ""
      host: mediaserver.local
      ip: 192.168.3.92
      port: 22
      username: serveradmin
      password: HCdqjDM7T$9jnVXqVM4uB!sDqsnpwJ